[project]
name = "rl-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "d3rlpy>=2.8.1",
    "matplotlib>=3.10.8",
    "msgpack>=1.1.2",
    "msgpack-numpy>=0.4.8",
    "numpy>=2.4.1",
    "pyzmq>=27.1.0",
]
