slam_toolbox:
  ros__parameters:
    use_sim_time: true

    mode: mapping        # mapping | localization
    scan_topic: /marble_hd2/scan

    map_frame: map
    odom_frame: odom
    base_frame: base_link

    resolution: 0.05

    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2

    do_loop_closing: true
    loop_search_maximum_distance: 3.0
